pelican:
  whoami: production
  target: asf-site
publish:
  whoami: asf-site

github:
  labels:
    - lucene
    - website
    - pelican
  enabled_merge_buttons:
    squash: true
    merge:  false
    rebase: false