pelican:
  whoami: main/lucene
  target: asf-staging-lucene

staging:
  whoami: asf-staging-lucene
  profile: new

github:
  labels:
    - apache
    - lucene
    - website
    - pelican
  enabled_merge_buttons:
    squash: true
    merge:  true
    rebase: false
  protected_branches:
    main
    production
