pelican:
  whoami: production
  target: asf-site
publish:
  whoami: asf-site

github:
  labels:
    - apache
    - lucene
    - website
    - pelican
  enabled_merge_buttons:
    squash: true
    merge:  true
    rebase: false
  protected_branches:
    master
    production

